[package]
name = "terrain_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coloriz = {version = "^0.2.0", optional = true}

[features]
color = ["dep:coloriz"]